"""Conversational planning prompts for probing LLM planning-horizon representations.

The task metadata is intended for downstream controls: analyses can separate
time-horizon effects from task family, difficulty, domain, planning style,
stakes, urgency, reversibility, and how far the consequences reach.

Every task uses all supported time units and the same value grid, from one
second to thirty millennia. Task metadata never restricts the duration
range, including when the requested duration is implausible for the task.
In particular `temporal_horizon` is the duration the *author* expects the task
to take. It is a hand label written before any activation was measured, never a
model output, and nothing in the pipeline fits on it or uses it to choose which
horizons a task is crossed with; it exists so a recovered readout can be checked
against an independent expectation.

The set is 100 tasks in two halves, distinguished by `source_set`. The 50
`original` tasks are the ones the stated corpora have always carried, with
their wording frozen so cached activations stay valid. The 50
`continuum_expansion` tasks fill cells the original 50 leave empty - most
importantly the off-diagonal ones where stakes and duration disagree, such as
existential stakes resolved in seconds or negligible stakes pursued for
generations, because those are the cells that identify a stakes effect apart
from a duration effect.

`stakes` is an ordered ten-level scale; `stakes_score` is its integer position
and is derived from `stakes` rather than labelled separately, so the two can
never disagree.
"""


try:
    from .time_units import SUPPORTED_UNITS
except ImportError:  # Support direct dataset imports.
    from utils import SUPPORTED_UNITS  # type: ignore


# "horizon_free_addition" is used only by horizon_free_task_set, whose tasks are
# never crossed with a stated horizon.
SOURCE_SETS = ("original", "continuum_expansion", "horizon_free_addition")
COMPLEXITY_LEVELS = ("very_low", "low", "medium", "high", "very_high")
# Ordered worst-case severity. The integer score is the 1-based position.
STAKES_LEVELS = ("very_low", "low", "medium_low", "medium", "medium_high", "high",
                 "very_high", "catastrophic", "near_existential", "existential")
STAKES_SCORES = {level: index for index, level in enumerate(STAKES_LEVELS, start=1)}
# Who has to act, ordered by how much of the world has to agree to act at once.
AGENCY_LEVELS = ("individual", "household", "small_team", "community_group",
                 "organization", "multi_organization", "local_government",
                 "national_government", "international_coalition",
                 "global_coordination")
# Who bears the consequence, which is deliberately separate from who acts.
AFFECTED_SCOPES = ("self", "individual", "household", "small_group", "organization",
                   "community", "city_region", "national", "international", "global",
                   "civilization")
# The author's expected duration, never used to restrict the horizon grid.
TEMPORAL_HORIZONS = ("seconds_minutes", "minutes_hours", "hours_days", "days_weeks",
                     "weeks_months", "months_years", "years_decades", "generations")
PLANNING_TYPES = ("none", "procedural", "tactical", "project", "creative", "strategic",
                  "systems", "crisis_response")
URGENCY_LEVELS = ("none", "low", "moderate", "high", "immediate")
REVERSIBILITY_LEVELS = ("high", "medium", "low", "irreversible")
UNCERTAINTY_LEVELS = ("low", "medium", "high", "extreme")
COORDINATION_LOADS = ("none", "low", "medium", "high", "extreme")
SCENARIO_TYPES = ("routine", "preparation", "administrative", "decision", "planning",
                  "design", "creative", "simulation", "training", "communication",
                  "coordination", "inspection", "prevention", "continuity",
                  "emergency_response", "recovery", "restoration")
SCENARIO_REALISM = ("realistic", "plausible_hypothetical", "speculative", "fictional")
PRIMARY_CONSEQUENCES = ("quality", "inconvenience", "personal_development", "financial",
                        "legal_rights", "cultural", "organizational", "environmental",
                        "infrastructure", "health_safety", "security", "societal",
                        "civilizational", "mixed")

# Domains are open-ended - a new task may need a domain no earlier task used - so
# they are collected from the table below rather than fixed up front. Subdomains
# are finer still and are unique per task.
_VOCABULARIES = {
    "source_set": SOURCE_SETS,
    "complexity": COMPLEXITY_LEVELS,
    "difficulty": COMPLEXITY_LEVELS,
    "planning_type": PLANNING_TYPES,
    "stakes": STAKES_LEVELS,
    "agency": AGENCY_LEVELS,
    "temporal_horizon": TEMPORAL_HORIZONS,
    "affected_scope": AFFECTED_SCOPES,
    "urgency": URGENCY_LEVELS,
    "reversibility": REVERSIBILITY_LEVELS,
    "uncertainty": UNCERTAINTY_LEVELS,
    "coordination_load": COORDINATION_LOADS,
    "scenario_type": SCENARIO_TYPES,
    "scenario_realism": SCENARIO_REALISM,
    "primary_consequence": PRIMARY_CONSEQUENCES,
}


def validate_task_metadata(task: str, config: dict[str, object]) -> None:
    """Reject any label outside its vocabulary, so a typo cannot reach an analysis."""
    for field, allowed in _VOCABULARIES.items():
        if config[field] not in allowed:
            raise ValueError(f"Task {task!r}: {field}={config[field]!r} is not one of "
                             f"{allowed}")
    if not str(config["stakes_rationale"]).strip():
        raise ValueError(f"Task {task!r}: stakes_rationale must say why the stakes "
                         f"label was chosen")


def _task(
    *,
    source_set: str,
    task_family: str,
    complexity: str,
    difficulty: str,
    domain: str,
    subdomain: str,
    planning_type: str,
    stakes: str,
    agency: str,
    temporal_horizon: str,
    affected_scope: str,
    urgency: str,
    reversibility: str,
    uncertainty: str,
    coordination_load: str,
    scenario_type: str,
    scenario_realism: str,
    primary_consequence: str,
    stakes_rationale: str,
) -> dict[str, object]:
    return {
        "units": set(SUPPORTED_UNITS),
        "source_set": source_set,
        "task_family": task_family,
        "complexity": complexity,
        "difficulty": difficulty,
        "domain": domain,
        "subdomain": subdomain,
        "planning_type": planning_type,
        "stakes": stakes,
        "stakes_score": STAKES_SCORES[stakes],
        "agency": agency,
        "temporal_horizon": temporal_horizon,
        "affected_scope": affected_scope,
        "urgency": urgency,
        "reversibility": reversibility,
        "uncertainty": uncertainty,
        "coordination_load": coordination_load,
        "scenario_type": scenario_type,
        "scenario_realism": scenario_realism,
        "primary_consequence": primary_consequence,
        "stakes_rationale": stakes_rationale,
    }


prompt_framings = [
    {
        "id": "task_available_time",
        "body": """Task: {task}
Available time: {value} {unit}

Write a plan optimized for the available time.""",
    },
    {
        "id": "task_time_budget",
        "body": """Task: {task}
Time budget: {value} {unit}

Provide a plan that fits this time budget.""",
    },
    {
        "id": "task_deadline",
        "body": """Task: {task}
Deadline: {value} {unit} from now

Give a plan appropriate for this deadline.""",
    },
    {
        "id": "goal_available_time",
        "body": """Goal: {task}
Available time: {value} {unit}

Write a plan optimized for the available time.""",
    },
    {
        "id": "goal_time_budget",
        "body": """Goal: {task}
Time budget: {value} {unit}

Provide a plan that fits this time budget.""",
    },
    {
        "id": "goal_deadline",
        "body": """Goal: {task}
Deadline: {value} {unit} from now

Give a plan appropriate for this deadline.""",
    },
    {
        "id": "objective_available_time",
        "body": """Objective: {task}
Available time: {value} {unit}

Write a plan optimized for the available time.""",
    },
    {
        "id": "objective_time_budget",
        "body": """Objective: {task}
Time budget: {value} {unit}

Provide a plan that fits this time budget.""",
    },
    {
        "id": "objective_deadline",
        "body": """Objective: {task}
Deadline: {value} {unit} from now

Give a plan appropriate for this deadline.""",
    },
]


templates = [
    {
        "id": framing["id"],
        "template": framing["body"],
        "prompt_framing": framing["id"],
    }
    for framing in prompt_framings
]
tasks = {
    'answer a yes-or-no question': _task(
        source_set='original',
        task_family='information_handling',
        complexity='very_low',
        difficulty='very_low',
        domain='general',
        subdomain='basic_question_answering',
        planning_type='none',
        stakes='very_low',
        agency='individual',
        temporal_horizon='seconds_minutes',
        affected_scope='self',
        urgency='none',
        reversibility='high',
        uncertainty='low',
        coordination_load='none',
        scenario_type='routine',
        scenario_realism='realistic',
        primary_consequence='quality',
        stakes_rationale='An incorrect answer is normally easy to correct and has little impact.',
    ),
    'press a button when a light turns green': _task(
        source_set='original',
        task_family='routine_execution',
        complexity='very_low',
        difficulty='very_low',
        domain='general',
        subdomain='stimulus_response',
        planning_type='procedural',
        stakes='very_low',
        agency='individual',
        temporal_horizon='seconds_minutes',
        affected_scope='self',
        urgency='moderate',
        reversibility='high',
        uncertainty='low',
        coordination_load='none',
        scenario_type='routine',
        scenario_realism='realistic',
        primary_consequence='quality',
        stakes_rationale='The action is simple and no harmful consequence is specified.',
    ),
    'copy a short code from one screen to another': _task(
        source_set='original',
        task_family='information_handling',
        complexity='very_low',
        difficulty='very_low',
        domain='office_administration',
        subdomain='data_entry',
        planning_type='procedural',
        stakes='very_low',
        agency='individual',
        temporal_horizon='seconds_minutes',
        affected_scope='individual',
        urgency='low',
        reversibility='high',
        uncertainty='low',
        coordination_load='none',
        scenario_type='routine',
        scenario_realism='realistic',
        primary_consequence='quality',
        stakes_rationale='A transcription error is usually detectable and reversible.',
    ),
    'choose between two lunch options': _task(
        source_set='original',
        task_family='personal_choice',
        complexity='very_low',
        difficulty='very_low',
        domain='personal_life',
        subdomain='meal_choice',
        planning_type='none',
        stakes='very_low',
        agency='individual',
        temporal_horizon='seconds_minutes',
        affected_scope='self',
        urgency='none',
        reversibility='high',
        uncertainty='low',
        coordination_load='none',
        scenario_type='decision',
        scenario_realism='realistic',
        primary_consequence='inconvenience',
        stakes_rationale='The choice has small and short-lived personal consequences.',
    ),
    'make a cup of tea': _task(
        source_set='original',
        task_family='household_management',
        complexity='low',
        difficulty='low',
        domain='household',
        subdomain='beverage_preparation',
        planning_type='procedural',
        stakes='very_low',
        agency='individual',
        temporal_horizon='seconds_minutes',
        affected_scope='self',
        urgency='low',
        reversibility='high',
        uncertainty='low',
        coordination_load='none',
        scenario_type='preparation',
        scenario_realism='realistic',
        primary_consequence='inconvenience',
        stakes_rationale='Failure generally causes only minor inconvenience or waste.',
    ),
    'pack a bag with essentials for the day': _task(
        source_set='original',
        task_family='personal_logistics',
        complexity='low',
        difficulty='low',
        domain='personal_life',
        subdomain='daily_preparation',
        planning_type='tactical',
        stakes='low',
        agency='individual',
        temporal_horizon='seconds_minutes',
        affected_scope='individual',
        urgency='moderate',
        reversibility='high',
        uncertainty='low',
        coordination_load='none',
        scenario_type='preparation',
        scenario_realism='realistic',
        primary_consequence='inconvenience',
        stakes_rationale='Omissions may disrupt one day but are usually recoverable.',
    ),
    'tidy a desk before a meeting': _task(
        source_set='original',
        task_family='routine_execution',
        complexity='low',
        difficulty='very_low',
        domain='office_administration',
        subdomain='workspace_preparation',
        planning_type='procedural',
        stakes='very_low',
        agency='individual',
        temporal_horizon='seconds_minutes',
        affected_scope='self',
        urgency='low',
        reversibility='high',
        uncertainty='low',
        coordination_load='none',
        scenario_type='routine',
        scenario_realism='realistic',
        primary_consequence='quality',
        stakes_rationale='The main consequence is a small reduction in comfort or presentation quality.',
    ),
    'train for a marathon': _task(
        source_set='original',
        task_family='skill_development',
        complexity='high',
        difficulty='high',
        domain='sports_fitness',
        subdomain='endurance_training',
        planning_type='strategic',
        stakes='medium_low',
        agency='individual',
        temporal_horizon='months_years',
        affected_scope='individual',
        urgency='low',
        reversibility='medium',
        uncertainty='high',
        coordination_load='low',
        scenario_type='training',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='The task affects personal health and a substantial investment of time.',
    ),
    'plan an international trip': _task(
        source_set='original',
        task_family='project_planning',
        complexity='high',
        difficulty='medium',
        domain='travel_logistics',
        subdomain='international_travel',
        planning_type='project',
        stakes='medium',
        agency='household',
        temporal_horizon='weeks_months',
        affected_scope='household',
        urgency='low',
        reversibility='medium',
        uncertainty='medium',
        coordination_load='medium',
        scenario_type='planning',
        scenario_realism='realistic',
        primary_consequence='mixed',
        stakes_rationale='Errors can cause meaningful financial loss, disruption, or safety problems.',
    ),
    'organize a wedding for a friend': _task(
        source_set='original',
        task_family='event_coordination',
        complexity='high',
        difficulty='high',
        domain='events',
        subdomain='wedding_planning',
        planning_type='project',
        stakes='medium',
        agency='small_team',
        temporal_horizon='months_years',
        affected_scope='small_group',
        urgency='low',
        reversibility='medium',
        uncertainty='medium',
        coordination_load='high',
        scenario_type='coordination',
        scenario_realism='realistic',
        primary_consequence='mixed',
        stakes_rationale='Failure affects an important event, relationships, and substantial spending.',
    ),
    'plan a move to a new city': _task(
        source_set='original',
        task_family='personal_logistics',
        complexity='high',
        difficulty='high',
        domain='personal_life',
        subdomain='relocation',
        planning_type='project',
        stakes='medium_high',
        agency='household',
        temporal_horizon='months_years',
        affected_scope='household',
        urgency='low',
        reversibility='medium',
        uncertainty='high',
        coordination_load='medium',
        scenario_type='planning',
        scenario_realism='realistic',
        primary_consequence='mixed',
        stakes_rationale='The decision affects housing, work, finances, and social stability.',
    ),
    'build proficiency in a new language': _task(
        source_set='original',
        task_family='skill_development',
        complexity='high',
        difficulty='high',
        domain='education',
        subdomain='language_learning',
        planning_type='strategic',
        stakes='medium',
        agency='individual',
        temporal_horizon='months_years',
        affected_scope='individual',
        urgency='low',
        reversibility='high',
        uncertainty='medium',
        coordination_load='low',
        scenario_type='training',
        scenario_realism='realistic',
        primary_consequence='personal_development',
        stakes_rationale='Failure mainly loses time and foregone personal or professional opportunity.',
    ),
    'write a short story': _task(
        source_set='original',
        task_family='creative_production',
        complexity='medium',
        difficulty='medium',
        domain='creative_arts',
        subdomain='short_fiction',
        planning_type='creative',
        stakes='low',
        agency='individual',
        temporal_horizon='days_weeks',
        affected_scope='self',
        urgency='low',
        reversibility='high',
        uncertainty='high',
        coordination_load='low',
        scenario_type='creative',
        scenario_realism='realistic',
        primary_consequence='cultural',
        stakes_rationale='The output may matter personally but usually has limited external consequence.',
    ),
    'write a novel': _task(
        source_set='original',
        task_family='creative_production',
        complexity='very_high',
        difficulty='high',
        domain='creative_arts',
        subdomain='long_form_fiction',
        planning_type='creative',
        stakes='medium_low',
        agency='individual',
        temporal_horizon='months_years',
        affected_scope='self',
        urgency='low',
        reversibility='high',
        uncertainty='high',
        coordination_load='low',
        scenario_type='creative',
        scenario_realism='realistic',
        primary_consequence='cultural',
        stakes_rationale='The time investment is large while direct harm from failure remains limited.',
    ),
    'renovate an apartment': _task(
        source_set='original',
        task_family='built_environment_project',
        complexity='high',
        difficulty='high',
        domain='housing_construction',
        subdomain='residential_renovation',
        planning_type='project',
        stakes='medium_high',
        agency='household',
        temporal_horizon='months_years',
        affected_scope='household',
        urgency='moderate',
        reversibility='low',
        uncertainty='high',
        coordination_load='high',
        scenario_type='design',
        scenario_realism='realistic',
        primary_consequence='mixed',
        stakes_rationale='Mistakes can create costly, disruptive, or unsafe living conditions.',
    ),
    'develop a long-term personal investment strategy': _task(
        source_set='original',
        task_family='strategic_planning',
        complexity='high',
        difficulty='high',
        domain='finance',
        subdomain='personal_investment',
        planning_type='strategic',
        stakes='high',
        agency='individual',
        temporal_horizon='years_decades',
        affected_scope='household',
        urgency='low',
        reversibility='low',
        uncertainty='high',
        coordination_load='medium',
        scenario_type='planning',
        scenario_realism='realistic',
        primary_consequence='financial',
        stakes_rationale='Poor choices can materially affect long-term financial security.',
    ),
    'expand a local business to new markets': _task(
        source_set='original',
        task_family='strategic_planning',
        complexity='very_high',
        difficulty='high',
        domain='business',
        subdomain='market_expansion',
        planning_type='strategic',
        stakes='high',
        agency='organization',
        temporal_horizon='months_years',
        affected_scope='organization',
        urgency='low',
        reversibility='low',
        uncertainty='high',
        coordination_load='high',
        scenario_type='planning',
        scenario_realism='realistic',
        primary_consequence='organizational',
        stakes_rationale='Failure can threaten capital, jobs, and organizational survival.',
    ),
    'coordinate a disaster relief effort': _task(
        source_set='original',
        task_family='crisis_coordination',
        complexity='very_high',
        difficulty='very_high',
        domain='emergency_management',
        subdomain='disaster_relief',
        planning_type='crisis_response',
        stakes='very_high',
        agency='multi_organization',
        temporal_horizon='days_weeks',
        affected_scope='city_region',
        urgency='immediate',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='emergency_response',
        scenario_realism='plausible_hypothetical',
        primary_consequence='mixed',
        stakes_rationale='Coordination quality directly affects many lives during a regional disaster.',
    ),
    'establish a self-sustaining human settlement on another planet': _task(
        source_set='original',
        task_family='systems_design',
        complexity='very_high',
        difficulty='very_high',
        domain='space_systems',
        subdomain='extraterrestrial_settlement',
        planning_type='systems',
        stakes='catastrophic',
        agency='international_coalition',
        temporal_horizon='years_decades',
        affected_scope='global',
        urgency='low',
        reversibility='low',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='design',
        scenario_realism='speculative',
        primary_consequence='civilizational',
        stakes_rationale='Failure could destroy a settlement and a major civilizational investment.',
    ),
    'restore a degraded ecosystem to long-term stability': _task(
        source_set='original',
        task_family='environmental_stewardship',
        complexity='very_high',
        difficulty='high',
        domain='environment_climate',
        subdomain='ecosystem_restoration',
        planning_type='systems',
        stakes='very_high',
        agency='multi_organization',
        temporal_horizon='years_decades',
        affected_scope='city_region',
        urgency='low',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='restoration',
        scenario_realism='realistic',
        primary_consequence='environmental',
        stakes_rationale='The task affects biodiversity, livelihoods, and potentially irreversible ecological loss.',
    ),
    'design and build a city resilient to natural disasters': _task(
        source_set='original',
        task_family='systems_design',
        complexity='very_high',
        difficulty='very_high',
        domain='infrastructure_engineering',
        subdomain='resilient_city',
        planning_type='systems',
        stakes='very_high',
        agency='local_government',
        temporal_horizon='years_decades',
        affected_scope='city_region',
        urgency='low',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='design',
        scenario_realism='plausible_hypothetical',
        primary_consequence='infrastructure',
        stakes_rationale='Design failures can expose an entire city to repeated mass-casualty events.',
    ),
    'develop a long-term plan for safely containing hazardous materials': _task(
        source_set='original',
        task_family='safety_containment',
        complexity='very_high',
        difficulty='high',
        domain='hazardous_materials',
        subdomain='long_term_containment',
        planning_type='systems',
        stakes='catastrophic',
        agency='multi_organization',
        temporal_horizon='years_decades',
        affected_scope='city_region',
        urgency='moderate',
        reversibility='low',
        uncertainty='high',
        coordination_load='high',
        scenario_type='planning',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='Containment failure may cause severe, persistent harm across generations.',
    ),
    'design an institution for long-term stability and effectiveness': _task(
        source_set='original',
        task_family='institution_design',
        complexity='very_high',
        difficulty='high',
        domain='governance_institutions',
        subdomain='institutional_design',
        planning_type='systems',
        stakes='high',
        agency='organization',
        temporal_horizon='years_decades',
        affected_scope='organization',
        urgency='low',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='design',
        scenario_realism='realistic',
        primary_consequence='organizational',
        stakes_rationale='The design shapes long-run outcomes for many members and successors.',
    ),
    "develop a long-term strategy for humanity's survival": _task(
        source_set='original',
        task_family='resilience_planning',
        complexity='very_high',
        difficulty='very_high',
        domain='existential_risk',
        subdomain='human_survival',
        planning_type='systems',
        stakes='existential',
        agency='global_coordination',
        temporal_horizon='generations',
        affected_scope='civilization',
        urgency='low',
        reversibility='irreversible',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='planning',
        scenario_realism='speculative',
        primary_consequence='civilizational',
        stakes_rationale='The explicit objective is preventing permanent human extinction.',
    ),
    'design infrastructure resilient to climate change': _task(
        source_set='original',
        task_family='resilience_planning',
        complexity='very_high',
        difficulty='very_high',
        domain='environment_climate',
        subdomain='climate_resilient_infrastructure',
        planning_type='systems',
        stakes='catastrophic',
        agency='national_government',
        temporal_horizon='years_decades',
        affected_scope='national',
        urgency='moderate',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='design',
        scenario_realism='realistic',
        primary_consequence='infrastructure',
        stakes_rationale='Failures can expose large populations to persistent climate hazards.',
    ),
    'design a communication plan for a company restructuring': _task(
        source_set='original',
        task_family='communication',
        complexity='high',
        difficulty='medium',
        domain='corporate_communications',
        subdomain='restructuring_communication',
        planning_type='strategic',
        stakes='medium_high',
        agency='organization',
        temporal_horizon='weeks_months',
        affected_scope='organization',
        urgency='moderate',
        reversibility='medium',
        uncertainty='high',
        coordination_load='high',
        scenario_type='communication',
        scenario_realism='realistic',
        primary_consequence='organizational',
        stakes_rationale='Poor communication can damage livelihoods, trust, and organizational continuity.',
    ),
    'create a single-page personal website': _task(
        source_set='original',
        task_family='digital_creation',
        complexity='medium',
        difficulty='low',
        domain='software_web',
        subdomain='personal_website',
        planning_type='project',
        stakes='low',
        agency='individual',
        temporal_horizon='days_weeks',
        affected_scope='self',
        urgency='low',
        reversibility='high',
        uncertainty='medium',
        coordination_load='low',
        scenario_type='design',
        scenario_realism='realistic',
        primary_consequence='quality',
        stakes_rationale='Failure primarily affects presentation and a modest amount of effort.',
    ),
    'preserve a small folder of important documents': _task(
        source_set='original',
        task_family='data_protection',
        complexity='low',
        difficulty='low',
        domain='information_knowledge',
        subdomain='personal_records',
        planning_type='procedural',
        stakes='medium_low',
        agency='individual',
        temporal_horizon='hours_days',
        affected_scope='individual',
        urgency='low',
        reversibility='low',
        uncertainty='low',
        coordination_load='low',
        scenario_type='prevention',
        scenario_realism='realistic',
        primary_consequence='mixed',
        stakes_rationale='Loss could cause meaningful personal administrative or financial problems.',
    ),
    "develop a process to preserve an organization's records for future teams": _task(
        source_set='original',
        task_family='knowledge_preservation',
        complexity='high',
        difficulty='medium',
        domain='information_knowledge',
        subdomain='organizational_records',
        planning_type='systems',
        stakes='medium_high',
        agency='organization',
        temporal_horizon='months_years',
        affected_scope='organization',
        urgency='low',
        reversibility='medium',
        uncertainty='medium',
        coordination_load='high',
        scenario_type='design',
        scenario_realism='realistic',
        primary_consequence='organizational',
        stakes_rationale='Record loss can impair accountability and future organizational performance.',
    ),
    'design and preserve a knowledge archive for future civilizations': _task(
        source_set='original',
        task_family='knowledge_preservation',
        complexity='very_high',
        difficulty='very_high',
        domain='cultural_heritage',
        subdomain='civilization_archive',
        planning_type='systems',
        stakes='near_existential',
        agency='global_coordination',
        temporal_horizon='generations',
        affected_scope='civilization',
        urgency='low',
        reversibility='irreversible',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='design',
        scenario_realism='speculative',
        primary_consequence='civilizational',
        stakes_rationale='Failure could permanently erase knowledge needed by distant future societies.',
    ),
    'replace a lost identification card using a standard process': _task(
        source_set='original',
        task_family='administrative_process',
        complexity='low',
        difficulty='low',
        domain='public_administration',
        subdomain='identity_replacement',
        planning_type='procedural',
        stakes='medium_low',
        agency='individual',
        temporal_horizon='days_weeks',
        affected_scope='individual',
        urgency='moderate',
        reversibility='high',
        uncertainty='low',
        coordination_load='low',
        scenario_type='administrative',
        scenario_realism='realistic',
        primary_consequence='legal_rights',
        stakes_rationale='Delay can restrict access to services but the process is recoverable.',
    ),
    "activate a building's emergency alarm after confirming a fire": _task(
        source_set='original',
        task_family='emergency_response',
        complexity='low',
        difficulty='low',
        domain='fire_safety',
        subdomain='fire_alarm_activation',
        planning_type='procedural',
        stakes='high',
        agency='individual',
        temporal_horizon='seconds_minutes',
        affected_scope='community',
        urgency='immediate',
        reversibility='low',
        uncertainty='low',
        coordination_load='low',
        scenario_type='emergency_response',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='A delayed alarm can endanger every occupant of the building.',
    ),
    'follow a shutdown checklist for overheating laboratory equipment': _task(
        source_set='original',
        task_family='critical_system_intervention',
        complexity='medium',
        difficulty='medium',
        domain='laboratory_safety',
        subdomain='equipment_shutdown',
        planning_type='procedural',
        stakes='high',
        agency='small_team',
        temporal_horizon='seconds_minutes',
        affected_scope='organization',
        urgency='immediate',
        reversibility='low',
        uncertainty='low',
        coordination_load='low',
        scenario_type='emergency_response',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='Incorrect execution can cause injury, fire, or costly laboratory damage.',
    ),
    'trigger a preauthorized shutdown of a runaway autonomous weapons system': _task(
        source_set='original',
        task_family='critical_system_intervention',
        complexity='high',
        difficulty='high',
        domain='defense_security',
        subdomain='autonomous_weapons_shutdown',
        planning_type='procedural',
        stakes='catastrophic',
        agency='organization',
        temporal_horizon='seconds_minutes',
        affected_scope='international',
        urgency='immediate',
        reversibility='low',
        uncertainty='medium',
        coordination_load='high',
        scenario_type='emergency_response',
        scenario_realism='plausible_hypothetical',
        primary_consequence='security',
        stakes_rationale='Failure could allow autonomous violence to spread across a conflict.',
    ),
    'send a prewritten global warning for a confirmed extinction-level impact': _task(
        source_set='original',
        task_family='communication',
        complexity='medium',
        difficulty='medium',
        domain='space_systems',
        subdomain='extinction_warning',
        planning_type='procedural',
        stakes='existential',
        agency='organization',
        temporal_horizon='seconds_minutes',
        affected_scope='civilization',
        urgency='immediate',
        reversibility='irreversible',
        uncertainty='low',
        coordination_load='high',
        scenario_type='emergency_response',
        scenario_realism='plausible_hypothetical',
        primary_consequence='civilizational',
        stakes_rationale='The scenario explicitly threatens extinction and warning time cannot be recovered.',
    ),
    'organize a community board-game tournament': _task(
        source_set='original',
        task_family='event_coordination',
        complexity='high',
        difficulty='medium',
        domain='community_events',
        subdomain='recreation_event',
        planning_type='project',
        stakes='medium_low',
        agency='community_group',
        temporal_horizon='weeks_months',
        affected_scope='community',
        urgency='low',
        reversibility='medium',
        uncertainty='medium',
        coordination_load='high',
        scenario_type='coordination',
        scenario_realism='realistic',
        primary_consequence='cultural',
        stakes_rationale='Failure wastes resources and disappoints a community but causes little lasting harm.',
    ),
    'restore drinking-water distribution after a regional outage': _task(
        source_set='original',
        task_family='utility_recovery',
        complexity='very_high',
        difficulty='high',
        domain='energy_utilities',
        subdomain='regional_water_distribution',
        planning_type='crisis_response',
        stakes='very_high',
        agency='multi_organization',
        temporal_horizon='days_weeks',
        affected_scope='city_region',
        urgency='immediate',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='recovery',
        scenario_realism='plausible_hypothetical',
        primary_consequence='infrastructure',
        stakes_rationale='Prolonged failure threatens health and basic services across a region.',
    ),
    'execute a prepared evacuation plan for a confirmed planet-wide impact': _task(
        source_set='original',
        task_family='evacuation',
        complexity='very_high',
        difficulty='very_high',
        domain='space_systems',
        subdomain='planetary_evacuation',
        planning_type='crisis_response',
        stakes='existential',
        agency='global_coordination',
        temporal_horizon='hours_days',
        affected_scope='civilization',
        urgency='immediate',
        reversibility='irreversible',
        uncertainty='low',
        coordination_load='extreme',
        scenario_type='emergency_response',
        scenario_realism='speculative',
        primary_consequence='civilizational',
        stakes_rationale='Failure under a confirmed planetary threat could eliminate humanity.',
    ),
    'restore a failed component in a global biosecurity containment system': _task(
        source_set='original',
        task_family='system_recovery',
        complexity='very_high',
        difficulty='very_high',
        domain='biosecurity',
        subdomain='containment_infrastructure',
        planning_type='crisis_response',
        stakes='near_existential',
        agency='international_coalition',
        temporal_horizon='seconds_minutes',
        affected_scope='global',
        urgency='immediate',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='recovery',
        scenario_realism='plausible_hypothetical',
        primary_consequence='security',
        stakes_rationale='A failed global containment layer may permit an uncontrollable biological release.',
    ),
    'design a detailed ruleset for a fictional competitive league': _task(
        source_set='original',
        task_family='rules_simulation_design',
        complexity='high',
        difficulty='high',
        domain='game_design',
        subdomain='fictional_ruleset',
        planning_type='creative',
        stakes='low',
        agency='individual',
        temporal_horizon='months_years',
        affected_scope='small_group',
        urgency='low',
        reversibility='high',
        uncertainty='high',
        coordination_load='medium',
        scenario_type='creative',
        scenario_realism='fictional',
        primary_consequence='cultural',
        stakes_rationale='The work is complex but errors have limited real-world consequences.',
    ),
    "build a high-fidelity simulation of an imaginary city's transport network": _task(
        source_set='original',
        task_family='rules_simulation_design',
        complexity='very_high',
        difficulty='high',
        domain='transport_logistics',
        subdomain='fictional_transport_simulation',
        planning_type='systems',
        stakes='low',
        agency='small_team',
        temporal_horizon='months_years',
        affected_scope='small_group',
        urgency='low',
        reversibility='high',
        uncertainty='high',
        coordination_load='high',
        scenario_type='simulation',
        scenario_realism='fictional',
        primary_consequence='quality',
        stakes_rationale='High modeling difficulty is deliberately paired with low external stakes.',
    ),
    'coordinate international containment of a self-propagating engineered pathogen': _task(
        source_set='original',
        task_family='global_coordination',
        complexity='very_high',
        difficulty='very_high',
        domain='biosecurity',
        subdomain='engineered_pathogen_containment',
        planning_type='crisis_response',
        stakes='near_existential',
        agency='international_coalition',
        temporal_horizon='days_weeks',
        affected_scope='global',
        urgency='immediate',
        reversibility='irreversible',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='emergency_response',
        scenario_realism='plausible_hypothetical',
        primary_consequence='civilizational',
        stakes_rationale='Failure could cause irreversible worldwide biological catastrophe.',
    ),
    'develop a global response strategy for a newly detected extinction-level asteroid': _task(
        source_set='original',
        task_family='planetary_defense',
        complexity='very_high',
        difficulty='very_high',
        domain='space_systems',
        subdomain='extinction_asteroid_response',
        planning_type='systems',
        stakes='existential',
        agency='global_coordination',
        temporal_horizon='months_years',
        affected_scope='civilization',
        urgency='immediate',
        reversibility='irreversible',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='planning',
        scenario_realism='plausible_hypothetical',
        primary_consequence='civilizational',
        stakes_rationale='The hazard is explicitly capable of causing extinction.',
    ),
    'apply a validated patch that prevents an imminent uncontrolled nuclear escalation': _task(
        source_set='original',
        task_family='critical_system_intervention',
        complexity='high',
        difficulty='very_high',
        domain='defense_security',
        subdomain='nuclear_escalation_patch',
        planning_type='procedural',
        stakes='near_existential',
        agency='organization',
        temporal_horizon='seconds_minutes',
        affected_scope='global',
        urgency='immediate',
        reversibility='irreversible',
        uncertainty='low',
        coordination_load='high',
        scenario_type='emergency_response',
        scenario_realism='plausible_hypothetical',
        primary_consequence='civilizational',
        stakes_rationale='A failed intervention could trigger global nuclear escalation.',
    ),
    'restart a planetary-defense tracking network using its tested recovery procedure': _task(
        source_set='original',
        task_family='system_recovery',
        complexity='high',
        difficulty='high',
        domain='space_infrastructure',
        subdomain='planetary_tracking_recovery',
        planning_type='procedural',
        stakes='catastrophic',
        agency='international_coalition',
        temporal_horizon='hours_days',
        affected_scope='global',
        urgency='immediate',
        reversibility='low',
        uncertainty='low',
        coordination_load='high',
        scenario_type='recovery',
        scenario_realism='plausible_hypothetical',
        primary_consequence='security',
        stakes_rationale='Loss of global tracking could leave catastrophic impacts undetected.',
    ),
    'coordinate deployment of a proven atmospheric intervention after a supervolcanic eruption': _task(
        source_set='original',
        task_family='crisis_coordination',
        complexity='very_high',
        difficulty='very_high',
        domain='environment_climate',
        subdomain='supervolcanic_response',
        planning_type='crisis_response',
        stakes='near_existential',
        agency='global_coordination',
        temporal_horizon='weeks_months',
        affected_scope='global',
        urgency='immediate',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='emergency_response',
        scenario_realism='plausible_hypothetical',
        primary_consequence='civilizational',
        stakes_rationale='Failure could allow a global climate and food-system catastrophe to deepen.',
    ),
    'simulate the complete history of a richly detailed fictional civilization': _task(
        source_set='original',
        task_family='creative_production',
        complexity='very_high',
        difficulty='very_high',
        domain='creative_arts',
        subdomain='fictional_civilization_simulation',
        planning_type='creative',
        stakes='low',
        agency='individual',
        temporal_horizon='years_decades',
        affected_scope='self',
        urgency='low',
        reversibility='high',
        uncertainty='extreme',
        coordination_load='medium',
        scenario_type='simulation',
        scenario_realism='fictional',
        primary_consequence='cultural',
        stakes_rationale='Extreme complexity is paired with negligible direct real-world harm.',
    ),
    'design an exhaustive taxonomy for an open-ended generative art universe': _task(
        source_set='original',
        task_family='rules_simulation_design',
        complexity='very_high',
        difficulty='high',
        domain='creative_arts',
        subdomain='generative_art_taxonomy',
        planning_type='systems',
        stakes='low',
        agency='small_team',
        temporal_horizon='months_years',
        affected_scope='small_group',
        urgency='low',
        reversibility='high',
        uncertainty='high',
        coordination_load='medium',
        scenario_type='design',
        scenario_realism='fictional',
        primary_consequence='cultural',
        stakes_rationale='Failure reduces coherence or usefulness but does not threaten welfare.',
    ),
    'coordinate worldwide preservation of public-domain cultural works': _task(
        source_set='original',
        task_family='knowledge_preservation',
        complexity='very_high',
        difficulty='high',
        domain='cultural_heritage',
        subdomain='global_cultural_preservation',
        planning_type='systems',
        stakes='high',
        agency='global_coordination',
        temporal_horizon='years_decades',
        affected_scope='global',
        urgency='low',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='coordination',
        scenario_realism='realistic',
        primary_consequence='cultural',
        stakes_rationale='Failure could cause widespread and irreversible cultural loss.',
    ),
    'design a globally interoperable scientific metadata system': _task(
        source_set='original',
        task_family='research_infrastructure',
        complexity='very_high',
        difficulty='very_high',
        domain='science_research',
        subdomain='scientific_metadata_standard',
        planning_type='systems',
        stakes='high',
        agency='international_coalition',
        temporal_horizon='years_decades',
        affected_scope='global',
        urgency='low',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='design',
        scenario_realism='realistic',
        primary_consequence='organizational',
        stakes_rationale='Poor design could impede worldwide research and knowledge integration for decades.',
    ),
    'choose background music for a casual dinner': _task(
        source_set='continuum_expansion',
        task_family='personal_choice',
        complexity='very_low',
        difficulty='very_low',
        domain='hospitality',
        subdomain='music_selection',
        planning_type='none',
        stakes='very_low',
        agency='individual',
        temporal_horizon='seconds_minutes',
        affected_scope='small_group',
        urgency='none',
        reversibility='high',
        uncertainty='low',
        coordination_load='none',
        scenario_type='decision',
        scenario_realism='realistic',
        primary_consequence='inconvenience',
        stakes_rationale='A poor choice has only a brief effect on enjoyment.',
    ),
    'correct a typo in an internal meeting agenda': _task(
        source_set='continuum_expansion',
        task_family='information_handling',
        complexity='very_low',
        difficulty='very_low',
        domain='office_administration',
        subdomain='document_correction',
        planning_type='procedural',
        stakes='very_low',
        agency='individual',
        temporal_horizon='seconds_minutes',
        affected_scope='organization',
        urgency='low',
        reversibility='high',
        uncertainty='low',
        coordination_load='none',
        scenario_type='routine',
        scenario_realism='realistic',
        primary_consequence='quality',
        stakes_rationale='The error is internal, visible, and easily corrected.',
    ),
    'return a library book before its due date': _task(
        source_set='continuum_expansion',
        task_family='administrative_process',
        complexity='very_low',
        difficulty='very_low',
        domain='library_services',
        subdomain='circulation',
        planning_type='procedural',
        stakes='low',
        agency='individual',
        temporal_horizon='days_weeks',
        affected_scope='individual',
        urgency='low',
        reversibility='high',
        uncertainty='low',
        coordination_load='low',
        scenario_type='administrative',
        scenario_realism='realistic',
        primary_consequence='inconvenience',
        stakes_rationale='Failure normally causes a small fee or inconvenience.',
    ),
    'sort recyclable waste for a small office': _task(
        source_set='continuum_expansion',
        task_family='routine_execution',
        complexity='low',
        difficulty='low',
        domain='waste_management',
        subdomain='waste_sorting',
        planning_type='procedural',
        stakes='low',
        agency='individual',
        temporal_horizon='hours_days',
        affected_scope='organization',
        urgency='low',
        reversibility='high',
        uncertainty='low',
        coordination_load='low',
        scenario_type='routine',
        scenario_realism='realistic',
        primary_consequence='environmental',
        stakes_rationale='One sorting error has a small, diffuse environmental cost.',
    ),
    'label materials for a classroom art activity': _task(
        source_set='continuum_expansion',
        task_family='information_handling',
        complexity='low',
        difficulty='low',
        domain='education',
        subdomain='classroom_materials',
        planning_type='procedural',
        stakes='low',
        agency='individual',
        temporal_horizon='hours_days',
        affected_scope='small_group',
        urgency='low',
        reversibility='high',
        uncertainty='low',
        coordination_load='low',
        scenario_type='preparation',
        scenario_realism='realistic',
        primary_consequence='quality',
        stakes_rationale='Errors cause confusion or minor waste within one class.',
    ),
    "back up a student's only current copy of a thesis before repairing their laptop": _task(
        source_set='continuum_expansion',
        task_family='data_protection',
        complexity='medium',
        difficulty='medium',
        domain='data_services',
        subdomain='critical_personal_backup',
        planning_type='procedural',
        stakes='medium',
        agency='individual',
        temporal_horizon='hours_days',
        affected_scope='individual',
        urgency='moderate',
        reversibility='low',
        uncertainty='low',
        coordination_load='low',
        scenario_type='prevention',
        scenario_realism='realistic',
        primary_consequence='personal_development',
        stakes_rationale="Failure could erase years of one person's academic work.",
    ),
    'prepare a household tax return involving ordinary employment income': _task(
        source_set='continuum_expansion',
        task_family='administrative_process',
        complexity='medium',
        difficulty='medium',
        domain='taxation',
        subdomain='household_tax_filing',
        planning_type='procedural',
        stakes='medium',
        agency='household',
        temporal_horizon='days_weeks',
        affected_scope='household',
        urgency='moderate',
        reversibility='medium',
        uncertainty='medium',
        coordination_load='low',
        scenario_type='administrative',
        scenario_realism='realistic',
        primary_consequence='financial',
        stakes_rationale='Errors may cause penalties, delays, or a correctable legal dispute.',
    ),
    'arrange accessibility accommodations for a small public event': _task(
        source_set='continuum_expansion',
        task_family='care_support',
        complexity='medium',
        difficulty='medium',
        domain='accessibility',
        subdomain='event_accessibility',
        planning_type='project',
        stakes='medium',
        agency='organization',
        temporal_horizon='days_weeks',
        affected_scope='small_group',
        urgency='moderate',
        reversibility='medium',
        uncertainty='medium',
        coordination_load='medium',
        scenario_type='coordination',
        scenario_realism='realistic',
        primary_consequence='legal_rights',
        stakes_rationale='Failure can exclude attendees or expose them to avoidable difficulty.',
    ),
    'find temporary housing for a family whose home needs urgent repairs': _task(
        source_set='continuum_expansion',
        task_family='care_support',
        complexity='high',
        difficulty='medium',
        domain='social_services',
        subdomain='emergency_housing',
        planning_type='tactical',
        stakes='medium_high',
        agency='community_group',
        temporal_horizon='days_weeks',
        affected_scope='household',
        urgency='high',
        reversibility='medium',
        uncertainty='high',
        coordination_load='medium',
        scenario_type='coordination',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='Failure can leave a family without safe shelter.',
    ),
    'transport an irreplaceable museum object using its standard handling procedure': _task(
        source_set='continuum_expansion',
        task_family='transport_operations',
        complexity='medium',
        difficulty='high',
        domain='cultural_heritage',
        subdomain='museum_object_transport',
        planning_type='procedural',
        stakes='medium_high',
        agency='organization',
        temporal_horizon='hours_days',
        affected_scope='organization',
        urgency='moderate',
        reversibility='low',
        uncertainty='low',
        coordination_load='medium',
        scenario_type='preparation',
        scenario_realism='realistic',
        primary_consequence='cultural',
        stakes_rationale='A handling error could permanently destroy a unique cultural object.',
    ),
    'prepare a meal for a guest with a documented severe food allergy': _task(
        source_set='continuum_expansion',
        task_family='medical_safety',
        complexity='medium',
        difficulty='medium',
        domain='food_agriculture',
        subdomain='allergen_control',
        planning_type='procedural',
        stakes='high',
        agency='individual',
        temporal_horizon='hours_days',
        affected_scope='individual',
        urgency='high',
        reversibility='low',
        uncertainty='low',
        coordination_load='low',
        scenario_type='prevention',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='A single ingredient error could cause severe injury or death.',
    ),
    'translate hospital discharge instructions for a patient who does not speak the local language': _task(
        source_set='continuum_expansion',
        task_family='medical_safety',
        complexity='medium',
        difficulty='high',
        domain='healthcare',
        subdomain='patient_communication',
        planning_type='procedural',
        stakes='high',
        agency='individual',
        temporal_horizon='hours_days',
        affected_scope='individual',
        urgency='high',
        reversibility='low',
        uncertainty='medium',
        coordination_load='low',
        scenario_type='communication',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='Miscommunication could cause dangerous medication or follow-up errors.',
    ),
    'decide whether an injured athlete requires urgent medical assessment': _task(
        source_set='continuum_expansion',
        task_family='medical_safety',
        complexity='medium',
        difficulty='high',
        domain='sports_fitness',
        subdomain='injury_triage',
        planning_type='tactical',
        stakes='high',
        agency='individual',
        temporal_horizon='seconds_minutes',
        affected_scope='individual',
        urgency='immediate',
        reversibility='low',
        uncertainty='high',
        coordination_load='low',
        scenario_type='decision',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='A mistaken decision could allow a serious injury to worsen.',
    ),
    'verify that a blood unit is correctly matched to a patient before transfusion': _task(
        source_set='continuum_expansion',
        task_family='medical_safety',
        complexity='medium',
        difficulty='high',
        domain='healthcare',
        subdomain='transfusion_verification',
        planning_type='procedural',
        stakes='very_high',
        agency='organization',
        temporal_horizon='seconds_minutes',
        affected_scope='individual',
        urgency='immediate',
        reversibility='low',
        uncertainty='low',
        coordination_load='low',
        scenario_type='prevention',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='A matching error can immediately kill or severely injure a patient.',
    ),
    'administer a prescribed rescue medication during a severe allergic reaction': _task(
        source_set='continuum_expansion',
        task_family='emergency_response',
        complexity='medium',
        difficulty='high',
        domain='healthcare',
        subdomain='allergy_rescue_medication',
        planning_type='procedural',
        stakes='very_high',
        agency='individual',
        temporal_horizon='seconds_minutes',
        affected_scope='individual',
        urgency='immediate',
        reversibility='low',
        uncertainty='low',
        coordination_load='low',
        scenario_type='emergency_response',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='Delay or incorrect administration can be fatal within minutes.',
    ),
    'locate a missing child during a supervised school outing': _task(
        source_set='continuum_expansion',
        task_family='emergency_response',
        complexity='high',
        difficulty='high',
        domain='education',
        subdomain='missing_child_response',
        planning_type='crisis_response',
        stakes='very_high',
        agency='small_team',
        temporal_horizon='minutes_hours',
        affected_scope='individual',
        urgency='immediate',
        reversibility='low',
        uncertainty='high',
        coordination_load='high',
        scenario_type='emergency_response',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='Delay increases the risk of serious harm to a child.',
    ),
    'coordinate the evacuation of a daycare after detecting a gas leak': _task(
        source_set='continuum_expansion',
        task_family='evacuation',
        complexity='high',
        difficulty='high',
        domain='education',
        subdomain='daycare_gas_evacuation',
        planning_type='crisis_response',
        stakes='very_high',
        agency='organization',
        temporal_horizon='seconds_minutes',
        affected_scope='small_group',
        urgency='immediate',
        reversibility='low',
        uncertainty='medium',
        coordination_load='high',
        scenario_type='emergency_response',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='Failure can expose many young children to fire or toxic gas.',
    ),
    'preserve chain of custody for evidence in a serious criminal case': _task(
        source_set='continuum_expansion',
        task_family='legal_evidence',
        complexity='high',
        difficulty='high',
        domain='criminal_justice',
        subdomain='evidence_custody',
        planning_type='procedural',
        stakes='high',
        agency='organization',
        temporal_horizon='months_years',
        affected_scope='small_group',
        urgency='moderate',
        reversibility='low',
        uncertainty='low',
        coordination_load='medium',
        scenario_type='prevention',
        scenario_realism='realistic',
        primary_consequence='legal_rights',
        stakes_rationale='A custody failure can compromise justice for victims and defendants.',
    ),
    'contain a foodborne illness outbreak linked to several restaurants': _task(
        source_set='continuum_expansion',
        task_family='public_health_response',
        complexity='high',
        difficulty='high',
        domain='public_health',
        subdomain='foodborne_outbreak',
        planning_type='crisis_response',
        stakes='very_high',
        agency='multi_organization',
        temporal_horizon='days_weeks',
        affected_scope='community',
        urgency='immediate',
        reversibility='low',
        uncertainty='high',
        coordination_load='high',
        scenario_type='emergency_response',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='Delay can expose a community and cause multiple severe illnesses.',
    ),
    'coordinate search and rescue for a missing fishing vessel': _task(
        source_set='continuum_expansion',
        task_family='crisis_coordination',
        complexity='very_high',
        difficulty='very_high',
        domain='maritime_transport',
        subdomain='maritime_search_rescue',
        planning_type='crisis_response',
        stakes='very_high',
        agency='multi_organization',
        temporal_horizon='hours_days',
        affected_scope='small_group',
        urgency='immediate',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='emergency_response',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='Operational failure can cost the lives of everyone aboard.',
    ),
    "validate a small company's payroll before employees are paid": _task(
        source_set='continuum_expansion',
        task_family='financial_operations',
        complexity='high',
        difficulty='medium',
        domain='workforce_operations',
        subdomain='payroll_validation',
        planning_type='procedural',
        stakes='medium_high',
        agency='organization',
        temporal_horizon='hours_days',
        affected_scope='organization',
        urgency='high',
        reversibility='medium',
        uncertainty='medium',
        coordination_load='medium',
        scenario_type='prevention',
        scenario_realism='realistic',
        primary_consequence='financial',
        stakes_rationale='Errors can disrupt the livelihoods of an entire workforce.',
    ),
    'investigate a laboratory sample mix-up before results are reported to patients': _task(
        source_set='continuum_expansion',
        task_family='quality_assurance',
        complexity='high',
        difficulty='high',
        domain='healthcare',
        subdomain='diagnostic_sample_integrity',
        planning_type='tactical',
        stakes='high',
        agency='organization',
        temporal_horizon='days_weeks',
        affected_scope='small_group',
        urgency='high',
        reversibility='medium',
        uncertainty='high',
        coordination_load='medium',
        scenario_type='inspection',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='Incorrect results could cause multiple patients to receive harmful care.',
    ),
    "recall a batch of children's products after discovering a safety defect": _task(
        source_set='continuum_expansion',
        task_family='product_safety',
        complexity='very_high',
        difficulty='high',
        domain='product_safety',
        subdomain='child_product_recall',
        planning_type='crisis_response',
        stakes='high',
        agency='organization',
        temporal_horizon='days_weeks',
        affected_scope='national',
        urgency='high',
        reversibility='low',
        uncertainty='high',
        coordination_load='high',
        scenario_type='prevention',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='Recall quality determines whether many children remain exposed to injury.',
    ),
    'inspect a school building after an earthquake and decide whether it can reopen': _task(
        source_set='continuum_expansion',
        task_family='inspection_assurance',
        complexity='high',
        difficulty='very_high',
        domain='infrastructure_engineering',
        subdomain='post_earthquake_school_inspection',
        planning_type='tactical',
        stakes='very_high',
        agency='local_government',
        temporal_horizon='hours_days',
        affected_scope='community',
        urgency='immediate',
        reversibility='low',
        uncertainty='high',
        coordination_load='medium',
        scenario_type='inspection',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='A false clearance can expose an entire school to structural collapse.',
    ),
    'evacuate a neighborhood after a hazardous chemical release': _task(
        source_set='continuum_expansion',
        task_family='evacuation',
        complexity='very_high',
        difficulty='high',
        domain='chemical_safety',
        subdomain='chemical_release_evacuation',
        planning_type='crisis_response',
        stakes='very_high',
        agency='local_government',
        temporal_horizon='seconds_minutes',
        affected_scope='community',
        urgency='immediate',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='emergency_response',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='Failure can cause mass exposure and persistent neighborhood contamination.',
    ),
    'reroute a regional commuter-rail network after a signaling-system failure': _task(
        source_set='continuum_expansion',
        task_family='transport_operations',
        complexity='very_high',
        difficulty='high',
        domain='rail_transport',
        subdomain='rail_disruption_management',
        planning_type='crisis_response',
        stakes='very_high',
        agency='organization',
        temporal_horizon='hours_days',
        affected_scope='city_region',
        urgency='immediate',
        reversibility='medium',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='emergency_response',
        scenario_realism='realistic',
        primary_consequence='infrastructure',
        stakes_rationale='Mistakes can strand thousands or create collision risk across the network.',
    ),
    'protect a regional hospital network during a ransomware attack': _task(
        source_set='continuum_expansion',
        task_family='cyber_incident_response',
        complexity='very_high',
        difficulty='very_high',
        domain='cybersecurity',
        subdomain='healthcare_ransomware',
        planning_type='crisis_response',
        stakes='very_high',
        agency='multi_organization',
        temporal_horizon='days_weeks',
        affected_scope='city_region',
        urgency='immediate',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='emergency_response',
        scenario_realism='realistic',
        primary_consequence='mixed',
        stakes_rationale='System loss can interrupt urgent care for a large regional population.',
    ),
    'contain a wildfire approaching several populated communities': _task(
        source_set='continuum_expansion',
        task_family='crisis_coordination',
        complexity='very_high',
        difficulty='very_high',
        domain='wildfire_management',
        subdomain='wildland_urban_fire',
        planning_type='crisis_response',
        stakes='very_high',
        agency='multi_organization',
        temporal_horizon='days_weeks',
        affected_scope='city_region',
        urgency='immediate',
        reversibility='low',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='emergency_response',
        scenario_realism='realistic',
        primary_consequence='mixed',
        stakes_rationale='Failure threatens multiple communities, ecosystems, and critical infrastructure.',
    ),
    'order the evacuation of a town downstream of a dam showing signs of failure': _task(
        source_set='continuum_expansion',
        task_family='evacuation',
        complexity='very_high',
        difficulty='very_high',
        domain='infrastructure_engineering',
        subdomain='dam_failure_evacuation',
        planning_type='crisis_response',
        stakes='catastrophic',
        agency='local_government',
        temporal_horizon='seconds_minutes',
        affected_scope='city_region',
        urgency='immediate',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='emergency_response',
        scenario_realism='plausible_hypothetical',
        primary_consequence='health_safety',
        stakes_rationale='A delayed or mistaken decision can produce mass casualties.',
    ),
    'restore power to hospitals and water facilities during a multi-county blackout': _task(
        source_set='continuum_expansion',
        task_family='utility_recovery',
        complexity='very_high',
        difficulty='very_high',
        domain='energy_utilities',
        subdomain='critical_service_power_restoration',
        planning_type='crisis_response',
        stakes='catastrophic',
        agency='multi_organization',
        temporal_horizon='days_weeks',
        affected_scope='city_region',
        urgency='immediate',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='recovery',
        scenario_realism='plausible_hypothetical',
        primary_consequence='infrastructure',
        stakes_rationale='Prolonged outage can cause cascading failures in life-sustaining services.',
    ),
    'ground a national aircraft fleet after evidence of a shared safety defect': _task(
        source_set='continuum_expansion',
        task_family='inspection_assurance',
        complexity='very_high',
        difficulty='very_high',
        domain='aviation_transport',
        subdomain='fleet_safety_grounding',
        planning_type='strategic',
        stakes='very_high',
        agency='national_government',
        temporal_horizon='hours_days',
        affected_scope='national',
        urgency='immediate',
        reversibility='medium',
        uncertainty='high',
        coordination_load='high',
        scenario_type='decision',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='The decision balances mass-casualty risk against nationwide disruption.',
    ),
    'coordinate a nationwide recall of contaminated infant formula': _task(
        source_set='continuum_expansion',
        task_family='product_safety',
        complexity='very_high',
        difficulty='very_high',
        domain='food_agriculture',
        subdomain='infant_formula_recall',
        planning_type='crisis_response',
        stakes='very_high',
        agency='national_government',
        temporal_horizon='days_weeks',
        affected_scope='national',
        urgency='immediate',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='prevention',
        scenario_realism='realistic',
        primary_consequence='health_safety',
        stakes_rationale='Failure could harm infants nationwide and disrupt essential nutrition.',
    ),
    'protect the integrity of vote counting during a close national election': _task(
        source_set='continuum_expansion',
        task_family='institution_design',
        complexity='very_high',
        difficulty='very_high',
        domain='democratic_governance',
        subdomain='election_integrity',
        planning_type='systems',
        stakes='catastrophic',
        agency='national_government',
        temporal_horizon='days_weeks',
        affected_scope='national',
        urgency='immediate',
        reversibility='low',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='prevention',
        scenario_realism='realistic',
        primary_consequence='societal',
        stakes_rationale='Failure could delegitimize government and trigger prolonged national instability.',
    ),
    'keep a national payment system operating during a coordinated cyberattack': _task(
        source_set='continuum_expansion',
        task_family='cyber_incident_response',
        complexity='very_high',
        difficulty='very_high',
        domain='financial_infrastructure',
        subdomain='national_payments_resilience',
        planning_type='crisis_response',
        stakes='catastrophic',
        agency='national_government',
        temporal_horizon='days_weeks',
        affected_scope='national',
        urgency='immediate',
        reversibility='low',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='continuity',
        scenario_realism='realistic',
        primary_consequence='infrastructure',
        stakes_rationale='A prolonged failure can halt commerce and destabilize essential services.',
    ),
    'allocate scarce vaccines during a fast-moving national epidemic': _task(
        source_set='continuum_expansion',
        task_family='public_health_response',
        complexity='very_high',
        difficulty='very_high',
        domain='public_health',
        subdomain='vaccine_allocation',
        planning_type='strategic',
        stakes='catastrophic',
        agency='national_government',
        temporal_horizon='weeks_months',
        affected_scope='national',
        urgency='immediate',
        reversibility='low',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='planning',
        scenario_realism='plausible_hypothetical',
        primary_consequence='health_safety',
        stakes_rationale='Allocation decisions directly affect mortality and epidemic control nationwide.',
    ),
    'coordinate cleanup of a major oil spill affecting several countries': _task(
        source_set='continuum_expansion',
        task_family='environmental_stewardship',
        complexity='very_high',
        difficulty='very_high',
        domain='environment_climate',
        subdomain='multinational_oil_spill',
        planning_type='crisis_response',
        stakes='very_high',
        agency='international_coalition',
        temporal_horizon='months_years',
        affected_scope='international',
        urgency='high',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='restoration',
        scenario_realism='plausible_hypothetical',
        primary_consequence='environmental',
        stakes_rationale='Failure can cause long-lived ecological and economic damage across borders.',
    ),
    'prevent a destructive crop pest from spreading across national borders': _task(
        source_set='continuum_expansion',
        task_family='public_health_response',
        complexity='very_high',
        difficulty='very_high',
        domain='food_agriculture',
        subdomain='transboundary_crop_pest',
        planning_type='systems',
        stakes='very_high',
        agency='international_coalition',
        temporal_horizon='weeks_months',
        affected_scope='international',
        urgency='high',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='prevention',
        scenario_realism='plausible_hypothetical',
        primary_consequence='environmental',
        stakes_rationale='Failure can destroy harvests and undermine food security in several countries.',
    ),
    'establish a humanitarian corridor for civilians trapped in a conventional war': _task(
        source_set='continuum_expansion',
        task_family='humanitarian_response',
        complexity='very_high',
        difficulty='very_high',
        domain='humanitarian_relief',
        subdomain='civilian_safe_passage',
        planning_type='crisis_response',
        stakes='catastrophic',
        agency='international_coalition',
        temporal_horizon='hours_days',
        affected_scope='city_region',
        urgency='immediate',
        reversibility='low',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='coordination',
        scenario_realism='plausible_hypothetical',
        primary_consequence='health_safety',
        stakes_rationale='Failure may expose a large civilian population to immediate violence or deprivation.',
    ),
    "coordinate several countries' power-grid defenses during a synchronized cyberattack": _task(
        source_set='continuum_expansion',
        task_family='cyber_incident_response',
        complexity='very_high',
        difficulty='very_high',
        domain='cybersecurity',
        subdomain='multinational_grid_attack',
        planning_type='crisis_response',
        stakes='catastrophic',
        agency='international_coalition',
        temporal_horizon='days_weeks',
        affected_scope='international',
        urgency='immediate',
        reversibility='low',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='continuity',
        scenario_realism='plausible_hypothetical',
        primary_consequence='infrastructure',
        stakes_rationale='Failure could create cascading outages across several national economies.',
    ),
    'negotiate a ceasefire to stop a large regional conventional war': _task(
        source_set='continuum_expansion',
        task_family='diplomacy',
        complexity='very_high',
        difficulty='very_high',
        domain='international_relations',
        subdomain='regional_war_ceasefire',
        planning_type='strategic',
        stakes='catastrophic',
        agency='international_coalition',
        temporal_horizon='weeks_months',
        affected_scope='international',
        urgency='immediate',
        reversibility='low',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='coordination',
        scenario_realism='plausible_hypothetical',
        primary_consequence='societal',
        stakes_rationale='Success or failure may determine mass casualties and regional stability.',
    ),
    'restore the global financial clearing system after a systemic cyber failure': _task(
        source_set='continuum_expansion',
        task_family='system_recovery',
        complexity='very_high',
        difficulty='very_high',
        domain='financial_infrastructure',
        subdomain='global_clearing_recovery',
        planning_type='crisis_response',
        stakes='catastrophic',
        agency='global_coordination',
        temporal_horizon='days_weeks',
        affected_scope='global',
        urgency='immediate',
        reversibility='low',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='recovery',
        scenario_realism='plausible_hypothetical',
        primary_consequence='infrastructure',
        stakes_rationale='Extended failure could freeze global trade and trigger worldwide economic collapse.',
    ),
    'restore global satellite navigation after a cascading orbital-debris event': _task(
        source_set='continuum_expansion',
        task_family='system_recovery',
        complexity='very_high',
        difficulty='very_high',
        domain='space_infrastructure',
        subdomain='satellite_navigation_recovery',
        planning_type='crisis_response',
        stakes='catastrophic',
        agency='international_coalition',
        temporal_horizon='months_years',
        affected_scope='global',
        urgency='immediate',
        reversibility='low',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='recovery',
        scenario_realism='plausible_hypothetical',
        primary_consequence='infrastructure',
        stakes_rationale='Navigation loss would disrupt transport, timing, finance, and emergency operations worldwide.',
    ),
    'protect power grids and satellites during an extreme solar storm': _task(
        source_set='continuum_expansion',
        task_family='resilience_planning',
        complexity='very_high',
        difficulty='very_high',
        domain='space_infrastructure',
        subdomain='space_weather_response',
        planning_type='crisis_response',
        stakes='catastrophic',
        agency='global_coordination',
        temporal_horizon='days_weeks',
        affected_scope='global',
        urgency='immediate',
        reversibility='low',
        uncertainty='high',
        coordination_load='extreme',
        scenario_type='prevention',
        scenario_realism='plausible_hypothetical',
        primary_consequence='infrastructure',
        stakes_rationale='Failure could disable critical infrastructure across much of the world.',
    ),
    'coordinate famine prevention after crop failures across several major food-producing regions': _task(
        source_set='continuum_expansion',
        task_family='food_security',
        complexity='very_high',
        difficulty='very_high',
        domain='global_food_security',
        subdomain='multi_breadbasket_failure',
        planning_type='systems',
        stakes='near_existential',
        agency='global_coordination',
        temporal_horizon='months_years',
        affected_scope='global',
        urgency='immediate',
        reversibility='low',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='coordination',
        scenario_realism='plausible_hypothetical',
        primary_consequence='civilizational',
        stakes_rationale='Failure could cause worldwide famine, conflict, and institutional collapse.',
    ),
    'contain a highly lethal pandemic while preserving essential global services': _task(
        source_set='continuum_expansion',
        task_family='global_coordination',
        complexity='very_high',
        difficulty='very_high',
        domain='public_health',
        subdomain='lethal_pandemic_containment',
        planning_type='crisis_response',
        stakes='near_existential',
        agency='global_coordination',
        temporal_horizon='months_years',
        affected_scope='global',
        urgency='immediate',
        reversibility='irreversible',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='continuity',
        scenario_realism='plausible_hypothetical',
        primary_consequence='civilizational',
        stakes_rationale='Failure could kill a large fraction of humanity and collapse essential systems.',
    ),
    'coordinate planetary defense against an asteroid expected to devastate a continent but not cause human extinction': _task(
        source_set='continuum_expansion',
        task_family='planetary_defense',
        complexity='very_high',
        difficulty='very_high',
        domain='space_systems',
        subdomain='continental_asteroid_response',
        planning_type='systems',
        stakes='near_existential',
        agency='global_coordination',
        temporal_horizon='months_years',
        affected_scope='global',
        urgency='immediate',
        reversibility='irreversible',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='coordination',
        scenario_realism='plausible_hypothetical',
        primary_consequence='civilizational',
        stakes_rationale='The impact is sub-extinction but could destroy countries and destabilize civilization.',
    ),
    'prevent further escalation after limited nuclear weapon use between nuclear-armed states': _task(
        source_set='continuum_expansion',
        task_family='diplomacy',
        complexity='very_high',
        difficulty='very_high',
        domain='nuclear_security',
        subdomain='post_nuclear_deescalation',
        planning_type='crisis_response',
        stakes='near_existential',
        agency='international_coalition',
        temporal_horizon='seconds_minutes',
        affected_scope='global',
        urgency='immediate',
        reversibility='irreversible',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='emergency_response',
        scenario_realism='plausible_hypothetical',
        primary_consequence='civilizational',
        stakes_rationale='Failure could convert a limited exchange into global nuclear catastrophe.',
    ),
    'maintain essential food, energy, and medical systems through a multi-year volcanic winter': _task(
        source_set='continuum_expansion',
        task_family='continuity_management',
        complexity='very_high',
        difficulty='very_high',
        domain='civil_continuity',
        subdomain='volcanic_winter_continuity',
        planning_type='systems',
        stakes='near_existential',
        agency='global_coordination',
        temporal_horizon='years_decades',
        affected_scope='global',
        urgency='immediate',
        reversibility='low',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='continuity',
        scenario_realism='plausible_hypothetical',
        primary_consequence='civilizational',
        stakes_rationale='System failure could cause mass mortality and permanent civilizational regression.',
    ),
    'contain an engineered crop pathogen threatening staple harvests on every continent': _task(
        source_set='continuum_expansion',
        task_family='food_security',
        complexity='very_high',
        difficulty='very_high',
        domain='biosecurity',
        subdomain='global_crop_pathogen',
        planning_type='crisis_response',
        stakes='near_existential',
        agency='global_coordination',
        temporal_horizon='months_years',
        affected_scope='global',
        urgency='immediate',
        reversibility='irreversible',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='emergency_response',
        scenario_realism='plausible_hypothetical',
        primary_consequence='civilizational',
        stakes_rationale='Failure could collapse global food production without directly causing immediate extinction.',
    ),
    'preserve international governance and critical supply networks during the simultaneous collapse of several major states': _task(
        source_set='continuum_expansion',
        task_family='continuity_management',
        complexity='very_high',
        difficulty='very_high',
        domain='civil_continuity',
        subdomain='multistate_collapse_continuity',
        planning_type='systems',
        stakes='near_existential',
        agency='global_coordination',
        temporal_horizon='years_decades',
        affected_scope='global',
        urgency='immediate',
        reversibility='low',
        uncertainty='extreme',
        coordination_load='extreme',
        scenario_type='continuity',
        scenario_realism='plausible_hypothetical',
        primary_consequence='civilizational',
        stakes_rationale='Failure could turn severe geopolitical collapse into irreversible civilizational breakdown.',
    ),
}

for _task_name, _config in tasks.items():
    validate_task_metadata(_task_name, _config)

DOMAINS = tuple(sorted({str(config["domain"]) for config in tasks.values()}))
STATED_TASKS = tuple(tasks)


# Retain every canonical named-period value (2, 3, 5, 6, 12, 15, 30), plus
# intermediate coverage and a one-unit minimum. Tests enforce cross-corpus matching.
values = [1, 2, 3, 5, 6, 10, 12, 15, 30]
